local lustache = require "lustache"
local parser = require "sql2lua.parser"
local table_concat = table.concat
local table_insert = table.insert

local queryfile = assert(io.open(arg[1], "r"))
local queryfile_content = queryfile:read("*all")
queryfile:close()

local queries = assert(parser(queryfile_content))

local env = {
	queries = queries,
	params = function (self)
		local params = {}
		for _, v in ipairs(self.parts) do
			if type(v) == "table" then table_insert(params, v.param) end
		end
		return table_concat(params, ", ")
	end,
	body = function (self)
		local statement = {}
		for _, v in ipairs (self.parts) do
			if type(v) == "table" then
				table_insert(statement, "escape(" .. v.param .. ")")
			else
				table_insert(statement, "\"" .. v .. "\"")
			end
		end
		return table_concat(statement, " ..\n\t\t")
	end
}

local template = [[
-- Autogenerated. Do not modify.

local type = type
local tostring = tostring

local function escape (val)
	local exp_type = type(val)
	if "number" == exp_type then
		return tostring(val)
	elseif "string" == exp_type then
		return "'" .. tostring((val:gsub("'", "''"))) .. "'"
	elseif "boolean" == exp_type then
		return val and "TRUE" or "FALSE"
	else
		return tostring(val)
	end
end

local _M = {}

{{#queries}}
function _M.{{name}} ({{params}})
	return {{&body}}
end

{{/queries}}
return _M
]]

io.stdout:write(lustache:render(template, env))
